---

blank_issues_enabled: false

contact_links:
  - name: New Issue
    url: https://nofusscomputing.com/git/nofusscomputing/website/issues/new
    about: Create a new issue at the repositories home.